version: "3"

services:
    app-django:
        build: ./app/
        restart: unless-stopped
        volumes:
            - static_volume:/opt/codeleap/static/
            - ./app/:/opt/codeleap/
        networks:
            - nginx_network
            - postgres_network
        depends_on:
            - postgres
        environment:
            # this should be True to work properly with docker
            - USE_DOCKER=True

            # don't run with debug turned on in production
            - DEBUG=False

            # database setup
            - DB_USER=admin
            - DB_PASSWORD=admin
            - DB_NAME=crud_app
            - DB_HOST=postgres

            # host allowed to access django (should be equal to nginx conf)
            - ALLOWED_HOST=localhost

    postgres:
        image: postgres:latest
        restart: unless-stopped
        networks:
            - postgres_network
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=crud_app

    nginx:
        build: ./nginx/
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            # host allowed to access django (should be equal to nginx conf)
            - SERVER_NAME=127.0.0.1
            - SERVER_PORT=80
        volumes:
            - static_volume:/opt/codeleap/static/
        depends_on:
            - app-django
        networks:
            - nginx_network


networks:
    nginx_network:
        driver: bridge

    postgres_network:
        driver: bridge

volumes:
    postgres_volume:
    static_volume:
